---
- name: Install common unix tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - htop-osx
    - wget
    - tree
    - cdrtools
    - redis
    - android-platform-tools
    - awscli

- name: Install development applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
   - google-chrome
   - atom
   - github-desktop
   - dash
   - iterm2
   - sublime-text
   - spotify
   - slack
   - vagrant
   - vmware-fusion
   - vmware-remote-console
   - docker
   - dropbox
   - kitematic
   - coconutbattery
   - android-platform-tools

# OS X config
- block:
    - name: Disable natural scrolling (Requires restart)
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false
        state: present
      tags: 'osx'

  rescue:
    - name: Scrolling value not availible
      debug:
        msg: "There was an error accessing com.apple.swipescrolldirection"
- block:
    - name: Disable autocorrect (Requires restart)
      osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
        state: present
      tags: 'osx'

  rescue:
    - name: Autocorrect value not availible
      debug:
        msg: "There was an error accessing NSAutomaticSpellingCorrectionEnabled"

# VCS config
- name: Create VCS folder
  file:
    path: "{{ ansible_env['HOME'] }}/development"
    state: directory

# Atom config
- block:
    - name: Install atom packages
      shell: /Applications/Atom.app/Contents/Resources/app/apm/bin/apm install --packages-file atom-packages
  rescue:
    - name: apm not availible
      debug:
        msg: "There was an error accessing apm"

- name: Create bash aliases
  template:
    src: bash_profile.j2
    dest: "{{ ansible_env['HOME'] }}/.bash_profile"
    owner: "{{ ansible_env['USER'] }}"
    group: staff
    mode: '0644'

# Sublime config
# - name: Generate Sublime user config
#   template:
#     src: sublime-settings.j2
#     dest: "/Users/{{ ansible_env['USER'] }}/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
#     owner: "{{ ansible_env['USER'] }}"
#     group: staff
#     mode: '0644'

# iTerm config
- name: Download iterm-colors
  git:
    repo: https://github.com/bahlo/iterm-colors.git
    dest: "{{ ansible_env['HOME'] }}/development/iterm-colors"
    version: master

# zsh config
- name: Install oh-my-zsh
  shell: curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  args:
    creates: ~/.oh-my-zsh
  when: lookup('env','TRAVIS') != 'true'

- name: Generate zsh config
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: 0644
    owner: "{{ ansible_env['USER'] }}"
  when: lookup('env','TRAVIS') != 'true'
