---

- name: Install weaveworks tap
  homebrew_tap:
    name: weaveworks/tap

- name: Install common unix tools
  homebrew:
    name: ['htop-osx', 'wget', 'tree', 'cdrtools', 'kubernetes-cli', 'aws-iam-authenticator', 'weaveworks/tap/eksctl', 'hey', 'stern', 'bash', 'bash-completion@2', 'ghz', 'cli53', 'telnet']
    state: present

- name: Update homebrew
  homebrew:
    update_homebrew: yes
  when: lookup('env','GITHUB_REPOSITORY') == 'brianannis/dotfiles'

- name: Install development applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
   - google-chrome
   - atom
   - github
   - dash
   - iterm2
   - sublime-text
   - spotify
   - slack
   # - vmware-fusion
   # - vmware-remote-console
   - docker
   - coconutbattery
   - hyper
   - macdown
   - postico
   - balenaetcher
   - ccmenu
   - insomnia
   - the-unarchiver
   # - sensiblesidebuttons
   - keybase
   - viscosity

# OS X config
- block:
    - name: Disable natural scrolling (Requires restart)
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false
        state: present
      tags: 'osx'

  rescue:
    - name: Scrolling value not availible
      debug:
        msg: "There was an error accessing com.apple.swipescrolldirection"
- block:
    - name: Disable autocorrect (Requires restart)
      osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
        state: present
      tags: 'osx'

  rescue:
    - name: Autocorrect value not availible
      debug:
        msg: "There was an error accessing NSAutomaticSpellingCorrectionEnabled"

# VCS config
- name: Create VCS folder
  file:
    path: "{{ ansible_env['HOME'] }}/development"
    state: directory

# Atom config
- block:
    - name: Install atom packages
      shell: /Applications/Atom.app/Contents/Resources/app/apm/bin/apm install sync-settings@5.0.1
  rescue:
    - name: apm not availible
      debug:
        msg: "There was an error accessing apm"

- name: Create bash aliases
  template:
    src: bash_profile.j2
    dest: "{{ ansible_env['HOME'] }}/.bash_profile"
    owner: "{{ ansible_env['USER'] }}"
    group: staff
    mode: '0644'

# Sublime config
# - name: Generate Sublime user config
#   template:
#     src: sublime-settings.j2
#     dest: "/Users/{{ ansible_env['USER'] }}/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
#     owner: "{{ ansible_env['USER'] }}"
#     group: staff
#     mode: '0644'

# iTerm config
- name: Download iterm-colors
  git:
    repo: https://github.com/bahlo/iterm-colors.git
    dest: "{{ ansible_env['HOME'] }}/development/iterm-colors"
    version: master

- name: Render iTerm preferences
  template:
    src: com.googlecode.iterm2.plist.j2
    dest: "{{ ansible_env['HOME'] }}/Documents/com.googlecode.iterm2.plist"
    owner: "{{ ansible_env['USER'] }}"
    group: staff
    mode: '0644'

- name: Set iTerm preferences directory
  shell: defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "{{ ansible_env['HOME'] }}/Documents"

- name: Enable iTerm preferences loading
  shell: defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

- name: Install complete-alias
  get_url:
    url: https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias
    dest: "{{ ansible_env['HOME'] }}/.bash_completion"

- name: Add complete_aliases in bash_completion
  blockinfile:
    path: "{{ ansible_env['HOME'] }}/.bash_completion"
    block: |
      complete -F _complete_alias get
      complete -F _complete_alias describe
      complete -F _complete_alias apply
      complete -F _complete_alias namespace
      complete -F _complete_alias delete
      complete -C '/usr/local/bin/aws_completer' aws

## append /usr/local/bin/bash to /etc/shells
## chsh to /usr/local/bin/bash after run to upgrade from bash 3.x to 5.x

## brewed eksctl installs bash completion automatically now

- name: Copy hyper config
  copy:
    src: .hyper.js
    dest: "{{ ansible_env['HOME'] }}/.hyper.js"
    mode: '0644'

- name: Install python packages
  pip:
    name: ['awscli', 'boto3', 'netaddr']
    state: present
