---
# OS X config
- block:
    - name: disable natural scrolling
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false
        state: present
      tags: 'osx'

  rescue:
    - name: scrolling value not availible
      debug:
        msg: "There was an error accessing com.apple.swipescrolldirection"

- block:
    - name: disable autocorrect
      osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
        state: present
      tags: 'osx'

  rescue:
    - name: autocorrect value not availible
      debug:
        msg: "There was an error accessing NSAutomaticSpellingCorrectionEnabled"

- block:
    - name: set dock size
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: float
        value: 37
        state: present
      tags: 'dock'

  rescue:
    - name: Dock size value not availible
      debug:
        msg: "There was an error accessing com.apple.dock"

- block:
    - name: Set dock recent
      osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false
        state: present
      tags: 'dock'

  rescue:
    - name: dock recents value not availible
      debug:
        msg: "There was an error accessing com.apple.dock"

- block:
    - name: disable locale in com.apple.TextInputMenu
      osx_defaults:
        domain: com.apple.TextInputMenu
        key: visible
        type: int
        value: "0"
        state: present
      tags: 'menu'

    - name: disable airplay in com.apple.airplay
      osx_defaults:
        domain: com.apple.airplay
        key: showInMenuBarIfPresent
        type: bool
        value: false
        state: present
      tags: 'menu'

    - name: enable battery percentage in com.apple.menuextra.battery
      osx_defaults:
        domain: com.apple.menuextra.battery
        key: ShowPercent
        type: string
        value: "YES"
        state: present
      tags: 'menu'

    - name: set com.apple.systemuiserver
      osx_defaults:
        domain: com.apple.systemuiserver
        key: menuExtras
        type: array
        value:
          - "/System/Library/CoreServices/Menu Extras/User.menu"
          - "/System/Library/CoreServices/Menu Extras/Clock.menu"
          - "/System/Library/CoreServices/Menu Extras/Battery.menu"
          - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
          - "/System/Library/CoreServices/Menu Extras/VPN.menu"
          - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
        state: present
      tags: 'menu'

  rescue:
    - name: systemuiserver not availible
      debug:
        msg: "There was an error accessing com.apple.systemuiserver"

- block:
    - name: set column view in finder
      osx_defaults:
        domain: com.apple.Finder
        key: FXPreferredViewStyle
        type: string
        value: clmv
        state: present
      tags: 'finder'

  rescue:
    - name: finder view value not availible
      debug:
        msg: "There was an error accessing com.apple.Finder"

- block:
    - name: set NewWindowTarget in finder
      osx_defaults:
        domain: com.apple.Finder
        key: NewWindowTarget
        type: string
        value: PfHm
        state: present
      tags: 'finder'

  rescue:
    - name: finder NewWindowTarget value not availible
      debug:
        msg: "There was an error accessing com.apple.Finder"

- block:
    - name: turn off time machine for new disks
      osx_defaults:
        domain: com.apple.TimeMachine
        key: DoNotOfferNewDisksForBackup
        type: bool
        value: true
        state: present
      tags: 'timemachine'

  rescue:
    - name: com.apple.TimeMachine value not availible
      debug:
        msg: "there was an error accessing com.apple.Finder"
