---
- name: Install common unix tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - htop-osx
    - wget
    - tree

# OS X config
- block:
    - name: Read natural scrolling value
      shell: defaults read NSGlobalDomain com.apple.swipescrolldirection
      register: nsval

    - name: Check output
      debug: msg="{{nsval}}"

    - name: Disable natural scrolling (Requires restart)
      shell: defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
      when: nsval.stdout != '0'

  rescue:
    - name: Scrolling value not availible
      debug:
        msg: "There was an error accessing com.apple.swipescrolldirection"

# development config
- name: Create VCS folder
  file:
    path: "{{ ansible_env['HOME'] }}/development"
    state: directory

- name: Install oh-my-zsh
  shell: curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  args:
    creates: ~/.oh-my-zsh
  when: lookup('env','TRAVIS') != 'true'

- name: Generate zsh config
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: 0644
    owner: "{{ ansible_env['USER'] }}"
