---
# tasks file for atom

- name: install atom application
  homebrew_cask:
    name: 'atom'
    state: present

- block:
    - name: Install atom packages
      shell: /Applications/Atom.app/Contents/Resources/app/apm/bin/apm install sync-settings@5.0.1
  rescue:
    - name: apm not availible
      debug:
        msg: "There was an error accessing apm"
