---
# tasks file for apps

- name: Install taps
  community.general.homebrew_tap:
    name: weaveworks/tap,aws/tap

- name: Install common unix tools
  community.general.homebrew:
    name:
      - aws/tap/eks-node-viewer
      - awscli
      - cdrtools
      - cli53
      - docker-credential-helper-ecr
      - dive
      - ghz
      - grpcurl
      - helm
      - hey
      - htop
      - kubernetes-cli
      - redis
      - stern
      - telnet
      - tree
      - uv
      - weaveworks/tap/eksctl
      - wget
    state: present

- name: Update homebrew
  community.general.homebrew:
    update_homebrew: true
  when: lookup('env','GITHUB_REPOSITORY') == 'brianannis/dotfiles'

- name: Install development applications
  community.general.homebrew_cask:
    name:
      - android-file-transfer
      - balenaetcher
      - ccmenu
      - coconutbattery
      - dash
      - discord
      - docker-desktop
      - github
      - insomnia
      - linearmouse
      - multipass
      - postico
      - postman
      - spotify
      - the-unarchiver
      - visual-studio-code
    state: present
  ignore_errors: true
