---
# tasks file for apps

- name: install weaveworks tap
  homebrew_tap:
    name: weaveworks/tap

- name: install common unix tools
  homebrew:
    name: ['awscli', 'htop-osx', 'wget', 'tree', 'cdrtools', 'kubernetes-cli', 'weaveworks/tap/eksctl', 'hey', 'stern', 'bash', 'bash-completion@2', 'ghz', 'cli53', 'telnet', 'helm', 'docker-credential-helper-ecr']
    state: present

- name: update homebrew
  homebrew:
    update_homebrew: yes
  when: lookup('env','GITHUB_REPOSITORY') == 'brianannis/dotfiles'

## rm chome / slack

- name: install development applications
  homebrew_cask:
    name: ['github', 'dash', 'spotify', 'vmware-fusion', 'docker', 'coconutbattery', 'linearmouse', 'postico', 'balenaetcher', 'ccmenu', 'insomnia', 'the-unarchiver', 'visual-studio-code', 'discord', 'postman', 'android-file-transfer']
    state: present
  ignore_errors: yes

- name: install python packages
  pip:
    name: ['boto3', 'netaddr', 'kubernetes-validate']
    state: present
