---
# tasks file for apps

- name: install taps
  community.general.homebrew_tap:
    name: weaveworks/tap,aws/tap

- name: install common unix tools
  community.general.homebrew:
    name: ['awscli', 'htop-osx', 'wget', 'tree', 'cdrtools', 'kubernetes-cli', 'weaveworks/tap/eksctl', 'hey', 'stern', 'bash', 'bash-completion@2', 'ghz', 'cli53', 'telnet', 'helm', 'docker-credential-helper-ecr', 'aws/tap/eks-node-viewer']
    state: present

- name: update homebrew
  community.general.homebrew:
    update_homebrew: true
  when: lookup('env','GITHUB_REPOSITORY') == 'brianannis/dotfiles'

- name: install development applications
  community.general.homebrew_cask:
    name: ['github', 'dash', 'spotify', 'vmware-fusion', 'docker', 'coconutbattery', 'linearmouse', 'postico', 'balenaetcher', 'ccmenu', 'insomnia', 'the-unarchiver', 'visual-studio-code', 'discord', 'postman', 'android-file-transfer']
    state: present
  ignore_errors: true

- name: install python packages
  ansible.builtin.pip:
    name: ['boto3', 'netaddr', 'kubernetes-validate']
    state: present
