---
# tasks file for apps

- name: install weaveworks tap
  homebrew_tap:
    name: weaveworks/tap

- name: install iterm2
  homebrew:
    name: 'iterm2'
    state: present

- name: install common unix tools
  homebrew:
    name: ['awscli', 'htop-osx', 'wget', 'tree', 'cdrtools', 'kubernetes-cli', 'weaveworks/tap/eksctl', 'hey', 'stern', 'bash', 'bash-completion@2', 'ghz', 'cli53', 'telnet']
    state: present

- name: update homebrew
  homebrew:
    update_homebrew: yes
  when: lookup('env','GITHUB_REPOSITORY') == 'brianannis/dotfiles'

- name: install development applications
  homebrew:
    name: ['google-chrome', 'github', 'dash', 'spotify', 'slack', 'vmware-fusion', 'docker', 'coconutbattery', 'hyper', 'macdown', 'postico', 'balenaetcher', 'ccmenu', 'insomnia', 'the-unarchiver', '- sensiblesidebuttons', 'keybase', 'viscosity']
    state: present
  ignore_errors: yes

- name: install python packages
  pip:
    name: ['boto3', 'netaddr', 'kubernetes-validate']
    state: present
