---
# tasks file for sublime

- block:
    - name: remove from quarantine
      shell: xattr -d com.apple.quarantine /Applications/Sublime\ Text.app

  rescue:
    - name: xattr value not availible
      debug:
        msg: "There was an error accessing xattr"

- name: open app
  shell: open /Applications/Sublime\ Text.app

- name: Pause for 30 seconds
  pause:
    seconds: 30

- name: close app
  shell: pkill -x "Sublime Text"

- name: install package control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ ansible_env['HOME'] }}/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"

- name: generate sublime package control config
  template:
    src: packagecontrol-settings.j2
    dest: "/Users/{{ ansible_env['USER'] }}/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings"
    owner: "{{ ansible_env['USER'] }}"
    group: staff
    mode: '0644'

- name: generate sublime user config
  template:
    src: sublime-settings.j2
    dest: "/Users/{{ ansible_env['USER'] }}/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
    owner: "{{ ansible_env['USER'] }}"
    group: staff
    mode: '0644'
