name: Main workflow
on: [push]
jobs:
  one:
    name: syntax check
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: setup ruby env
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: lint yaml set
        run: |
          gem install yaml-lint
          yaml-lint -i $GITHUB_WORKSPACE

      - name: Run bootstrap
        env:
          ANSIBLE_FORCE_COLOR: True
        run: |
          chmod a+x bootstrap.sh
          ./bootstrap.sh
  two:
    name: run non-app roles
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run bootstrap
        env:
          ANSIBLE_FORCE_COLOR: True
        run: |
          pip3 install ansible==2.9.13
          ansible-playbook launch.yml --skip-tags apps
