name: Main workflow
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: setup ruby env
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: lint yaml set
        run: |
          gem install yaml-lint
          yaml-lint -i $GITHUB_WORKSPACE

      - name: Run bootstrap
        run: |
          chmod a+x bootstrap.sh
          ./bootstrap.sh
          cat /usr/local/etc/bash_completion.d/eksctl
