## bump
name: Main workflow
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run bootstrap
        run:|
          chmod a+x bootstrap.sh
          ./bootstrap.sh
