name: Main workflow
on: [push]
jobs:
  one:
    name: syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: setup ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: lint yaml set
        run: |
          gem install yaml-lint
          yaml-lint -i $GITHUB_WORKSPACE

      - name: cancel job
        uses: andymckay/cancel-action@0.3
        if: ${{ failure() }}

  # two:
  #   name: run e2e bootstrap
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Run bootstrap
  #       env:
  #         ANSIBLE_FORCE_COLOR: True
  #       run: |
  #         chmod a+x bootstrap.zsh
  #         ./bootstrap.zsh

  three:
    name: run backup & restore
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run backup script
        run: |
          mkdir -p $HOME/{.aws,.kube,.ssh,.docker}
          touch $HOME/{.docker/config.json,.vault,.zprofile,.zshrc}
          brew install ccmenu
          defaults write net.sourceforge.cruisecontrol.CCMenu UseColorInMenuBar 0
          chmod a+x backup.zsh
          ./backup.zsh any-password
          echo -e "check volume contents"
          ls -lart /Volumes/transfer/
          echo -e "detach volume"
          hdiutil detach /Volumes/transfer

      - name: Run restore script
        run: |
          rm -rf $HOME/{.aws,.kube,.ssh,.docker,.vault,.zprofile,.zshrc}
          chmod a+x restore.zsh
          ./restore.zsh any-password
          echo -e "check CCMenu values"
          defaults read net.sourceforge.cruisecontrol.CCMenu UseColorInMenuBar
          echo -e "check home contents"
          ls -lart $HOME

  # three:
  #   name: run non-app roles
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master
  #
  #     - name: Run bootstrap
  #       env:
  #         ANSIBLE_FORCE_COLOR: True
  #       run: |
  #         pip3 install ansible==2.9.13
  #         ansible-playbook launch.yml --tags terminal
  #
  #     - name: cancel job
  #       uses: andymckay/cancel-action@0.2
  #       if: ${{ failure() }}
